"""Invented names for the simulated fleet: farms, regions, farmers and towers.

Every name here is fictional. Farmer emails use the reserved ``example.com`` domain.
"""

from __future__ import annotations

REGIONS = ["Northern Ranges", "Coastal Flats", "Central Basin", "Southern Downs"]

FARM_FIRST = [
    "Totara",
    "Kahikatea",
    "Matai",
    "Rimu",
    "Tussock",
    "Raupo",
    "Harakeke",
    "Manuka",
    "Kanuka",
    "Puriri",
    "Karaka",
    "Ngaio",
    "Cabbage Tree",
    "Flax",
    "Bellbird",
    "Fantail",
    "Kingfisher",
    "Stony",
    "Red Tussock",
    "Silver Creek",
    "Long Gully",
    "Burnt Hill",
    "Windy Point",
    "Clearwater",
    "Larch",
    "Willow",
    "Shingle",
    "Bracken",
    "Swamp Oak",
    "Three Pines",
    "Blue Ridge",
    "Mossy",
    "Copper",
    "Fernleaf",
    "Hawthorn",
    "Muddy Lane",
    "Pumice",
    "Saddleback",
    "Tarn",
    "Boulder",
]
FARM_SECOND = ["Downs", "Flats", "Station", "Hills", "Valley", "Creek", "Ridge", "Plains", "Farm", "Run"]

FIRST_NAMES = [
    "Aroha",
    "Ben",
    "Carla",
    "Dougal",
    "Erin",
    "Fergus",
    "Grace",
    "Hemi",
    "Isla",
    "Jack",
    "Kiri",
    "Liam",
    "Mere",
    "Nathan",
    "Olivia",
    "Pita",
    "Quinn",
    "Rosie",
    "Sam",
    "Tama",
    "Una",
    "Vaughan",
    "Wiremu",
    "Xander",
    "Yvonne",
    "Zac",
    "Alana",
    "Bruce",
    "Chloe",
    "Dean",
    "Ella",
    "Finn",
    "Gemma",
    "Hamish",
    "Ivy",
    "Jono",
    "Kate",
    "Logan",
    "Maia",
    "Ned",
]
LAST_NAMES = [
    "Ashby",
    "Blackwood",
    "Calder",
    "Dunmore",
    "Eastwick",
    "Fairlie",
    "Glenholm",
    "Hartley",
    "Inglis",
    "Jardine",
    "Kerrigan",
    "Lindsay",
    "McAlister",
    "Northcote",
    "Ormond",
    "Pennington",
    "Quarry",
    "Rangi",
    "Strachan",
    "Tolley",
    "Underhill",
    "Vickery",
    "Waddell",
    "Yarrow",
    "Ziegler",
    "Abernethy",
    "Brackley",
    "Cotter",
    "Drummond",
    "Elphick",
    "Fordyce",
    "Gowan",
    "Hollis",
    "Irvine",
    "Jessop",
    "Kinloch",
    "Leckie",
    "Munro",
    "Nairn",
    "Osgood",
]

TOWER_SPOTS = ["North ridge", "South paddock", "Woolshed", "Gully", "Top block", "River flat"]

FIRMWARE_LEGACY = "3.3.9"
FIRMWARE_STABLE = "3.4.1"
FIRMWARE_DECOY = "3.4.2"
FIRMWARE_BAD = "3.5.0"
FIRMWARE_VERSIONS = [FIRMWARE_LEGACY, FIRMWARE_STABLE, FIRMWARE_DECOY, FIRMWARE_BAD]
